### PR TITLE
Fix adding fax extension to ivr

### PR DESCRIPTION
**Pull request by ROMB**
Current code uses ivr_list. Should use ivr_get_details instead

### CODE REVIEW

**Comment by tm1000** [comment]
What's the reasoning? It looks like it's only getting the ID of the ivr so the functions look identical in their usage?

**Comment by ROMB** [comment]
ivr_list() was replaced by ivr_get_details(), so the reason is there is no ivr_list() anymore.

**Comment by tm1000** [comment]
Well then.... :blush:

**Comment by ROMB** [comment]
When this will be merged into release version? Really want to have this fix on one of my FreePBX installs to get rid of ivr fax issue.

**Comment by tm1000** [comment]
This was merged.

**Pull request closed without merging**
